services:
  - type: web
    name: contraco-manager
    env: docker
    region: frankfurt
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILE
        value: prod
      - key: SERVER_PORT
        value: 9090
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: DATABASE_URL
        fromDatabase:
          name: contraco-db
          property: connectionString
      - key: DATABASE_USER
        fromDatabase:
          name: contraco-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: contraco-db
          property: password
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: CORS_ALLOWED_METHODS
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - key: CORS_ALLOWED_HEADERS
        value: "*"
      - key: MAX_FILE_SIZE
        value: "10MB"
      - key: MAX_REQUEST_SIZE
        value: "10MB"

databases:
  - name: contraco-db
    region: frankfurt
    plan: starter 