services:
  - type: web
    name: contraco-manager
    env: docker
    region: singapore
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: "9090"
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://dpg-cub76m23esus73eqvj2g-a.singapore-postgres.render.com:5432/contraco_db_22vt"
      - key: SPRING_DATASOURCE_USERNAME
        value: "contraco_db_22vt_user"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "9PamPMBPoBaJKmBNDEnpnRqfvqAmZlBi"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: CORS_ALLOWED_METHODS
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - key: CORS_ALLOWED_HEADERS
        value: "*"
      - key: MAX_FILE_SIZE
        value: "10MB"
      - key: MAX_REQUEST_SIZE
        value: "10MB"

databases:
  - name: contraco-db
    region: singapore
    plan: starter 