services:
  - type: web
    name: contraco-manager
    env: docker
    region: frankfurt
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILE
        value: prod
      - key: SERVER_PORT
        value: 9090
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: contraco-db
          property: connectionString
      - key: DATABASE_USER
        fromDatabase:
          name: contraco-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: contraco-db
          property: password

databases:
  - name: contraco-db
    region: frankfurt
    plan: starter 