services:
  - type: web
    name: contraco-manager
    env: docker
    region: frankfurt
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: "9090"
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: DATABASE_URL
        value: "postgresql://contraco_db_user:W2DFBO0Iy17aK4qLHb5ML2f0GAEweT3O@dpg-cub3nkl6l47c739ufbp0-a.frankfurt-postgres.render.com/contraco_db"
      - key: DATABASE_USER
        value: "contraco_db_user"
      - key: DATABASE_PASSWORD
        value: "W2DFBO0Iy17aK4qLHb5ML2f0GAEweT3O"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: CORS_ALLOWED_METHODS
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - key: CORS_ALLOWED_HEADERS
        value: "*"
      - key: MAX_FILE_SIZE
        value: "10MB"
      - key: MAX_REQUEST_SIZE
        value: "10MB"

databases:
  - name: contraco-db
    region: frankfurt
    plan: starter 